" Standard noncompatible
set nocompatible
set rtp+=vader.vim
set rtp+=.
set rtp+=after
filetype plugin indent on
syntax enable

" Import package to test
packadd vader
packadd jupyter

" Reset variable
for [s:key, s:val] in items(g:jupyter_default_settings)
    let value = s:val
    execute 'let g:jupyter_' . s:key . ' = value'
endfor
